### ISSUE TITLE
Failed to activate the compile-watch package

### ISSUE THREAD

**Issue by HarveyTvT** [Arcath/compile-watch#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.198.0
**System**: linux 3.19.5-200.fc21.x86_64
**Thrown From**: [compile-watch](https://github.com/arcath/compile-watch) package, v0.1.0
### Stack Trace

Failed to activate the compile-watch package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at Object.module.exports.loadProjectConfig (/home/harveytvt/.atom/packages/compile-watch/lib/compile-watch.coffee:134:23)
    at Object.module.exports.activate (/home/harveytvt/.atom/packages/compile-watch/lib/compile-watch.coffee:35:12)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:242:19)
    at /usr/share/atom/resources/app.asar/src/package.js:223:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:215:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.6
compile-watch, v0.1.0
emmet, v2.3.9
localization, v1.16.1

# Dev
No dev packages
```

**Comment by adi-works** [comment]
Persists in 0.1.4 and Atom 1.0.6.

**Comment by vseehausen** [comment]
+1

**Comment by pvrt** [comment]
+1

**Comment by KeremTubluk** [comment]
This issue arise (in Atom 1.7.2) when the file being watched is open on startup.
