### ISSUE TITLE
erorr when compiling .scss with Atom 1.0

### ISSUE THREAD

**Issue by andrei-popa** [Arcath/compile-watch#3]
/bin/sh: /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/resources/app/apm/bin/node: No such file or directory

**Comment by kufuntu** [comment]
Same here

Command failed: /bin/sh -c "/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/resources/app/apm/bin/node" "/Users/andre/.atom/packages/compile-watch/node_modules/node-sass/bin/node-sass" "/Users/andre/Sites/PageTemplate/scss/styles.scss" "/Users/andre/Sites/PageTemplate/css/styles.css"
/bin/sh: /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/resources/app/apm/bin/node: No such file or directory

**Comment by Arcath** [comment]
Looks like the node binary isn't in the same place in MacOS as it is in Windows.

Could you run: `which apm` to find your apm location and post it here please?
And could you see if there is a node binary in the same folder?

**Comment by andrei-popa** [comment]
seems the path is /usr/local/bin/apm
yes, the node binary is also in /usr/local/bin/

**Comment by Arcath** [comment]
I will update the binary default to change per os but for now you can get it working by going into _settings -> Packages -> compile-watch settings_ and changing **Node Binary** to `/usr/local/bin/node`

**Comment by andrei-popa** [comment]
great, that did the trick!
thank you!

**Comment by tscheiki** [comment]
I changed my Node Binary to /usr/local/bin/node... Unfortunately I still get this error: 

Command failed: /bin/sh -c "/usr/local/bin/node" "/Users/mt/.atom/packages/sass-watch/node_modules/node-sass/bin/node-sass" "/Users/mt/Desktop/css/login.scss" "/Users/mt/Desktop/css/login.css"
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mt/.atom/packages/sass-watch/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by Arcath** [comment]
@tscheikm That is odd, what node version is your system binary?

That error is what you get if you try and require `node-sass` in atom (hence why I used a child_process) but I didn't think you could get it when running the cli tool.
