### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attach' of null

### ISSUE THREAD

**Issue by mihai-ionescu** [Arcath/compile-watch#6]
Just as a note, I had a crash when I opened a chrme tab, and editor stopped, and an alert with a message that said that editor has stopped, popped, and asked me if I want to wait or close editor. I chosed wait, and then closed the editor. 
1. Open editor
2. Open a .scss file and hit ctrl+shift+w to watch the file

**Atom Version**: 1.6.1
**System**: Ubuntu 14.04.4
**Thrown From**: [compile-watch](https://github.com/arcath/compile-watch) package, v0.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'attach' of null

```
At /home/mihai/.atom/packages/compile-watch/lib/compile-watch.coffee:57

TypeError: Cannot read property 'attach' of null
    at Object.module.exports.watchFile (/home/mihai/.atom/packages/compile-watch/lib/compile-watch.coffee:57:22)
    at atom-workspace.<anonymous> (/home/mihai/.atom/packages/compile-watch/lib/compile-watch.coffee:31:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -3:22.7.0 compile-watch:watch (atom-text-editor.editor.is-focused)
  4x -1:25 editor:copy-path (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:00.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:01.1.0 compile-watch:watch (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "symbols-view",
      "atom-ctags",
      "php-integrator-navigation",
      "php-integrator-base",
      "zephir",
      "sass-watch"
    ]
  },
  "compile-watch": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.7
compile-watch, v0.1.4
emmet, v2.4.3
language-volt, v0.2.2
linter, v1.11.4
linter-php, v1.2.0
linter-twig, v0.1.1
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by Arcath** [comment]
Sounds like compile-watch tried to bind to a chrome tab when it opened.

**Comment by mihai-ionescu** [comment]
That's strange because the tab that I opened had nothing to do with atom, I just clicked a link in a newspaper website.
